import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const monserrat = localFont({
  src: './fonts/Montserrat-SemiBold.ttf'
});

export const metadata: Metadata = {
  title: "Pro Perfumes",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <body className={`${ monserrat.className } antialiased`}>
        { children }
      </body>
    </html>
  );
}
